### ISSUE TITLE
avrdude 6.1 breaking changes

### ISSUE THREAD

**Issue by rosterloh** [deanmao/avrdude-rpi#4]
I've run a package update on my raspberry pi and now avrdude has been updated to version 6.1. I've followed the setup instructions again but this trick does not seem to work with a newer avrdude. Have you experienced this problem?

**Comment by LowPowerLab** [comment]
Same here with AVRDUDE 6.1, I think it requires a longer sleep delay, I changed this line in autoreset from 0.12 to 0.32 and it works:
def reset():
  ...
  time.sleep(0.32)

**Comment by rosterloh** [comment]
Works for me!
