### ISSUE TITLE
wrong reset order of GPIO output

### ISSUE THREAD

**Issue by make-ing** [deanmao/avrdude-rpi#5]
Hello,
i could not get this code to work, and after a little thinking i figured out the reset order of the GPIO pin was in the wrong order. You have to pull the reset pin low (at least for the arduino uno which i'm using). But in the reset function the pin is first set to high and then to low. After switching the the reset order from HIGH<->LOW to LOW<->HIGH it worked right away.

Is this wrong order really working for you out there?

But despite this small problem, thank you very much for this code.

**Comment by bphermansson** [comment]
It works with my home-made Duemilanove-clone.

**Comment by rin67630** [comment]
The original code was made to emulate DTR, which has the wrong logic.

It should work on the DTR pin of the Arduino, which has a 100nF capacitor to Rst. So you get a reset on the END of the positive pulse.

I prefer wiring the GPIO to reset directly, changing the logic to:
`def reset():
  pin = 11
  GPIO.setup(pin, GPIO.OUT)
  GPIO.output(pin, GPIO.LOW)
  time.sleep(0.12)
  GPIO.output(pin, GPIO.HIGH)
  GPIO.setup(pin, GPIO.IN)
`
Enjoy!

**Comment by rin67630** [comment]
By the way: this code in autoreset is universal: it will work on DTR and on Reset direct and with a condensator altogether. It just drives two pulses so you have a trigger in every direction:
`def reset():
  pin = 11
  GPIO.setup(pin, GPIO.OUT)
  GPIO.output(pin, GPIO.LOW)
  time.sleep(0.01)
  GPIO.output(pin, GPIO.HIGH)
  time.sleep(0.01)
  GPIO.output(pin, GPIO.LOW)
  time.sleep(0.01)
  GPIO.output(pin, GPIO.HIGH)
  GPIO.setup(pin, GPIO.IN)`
