### ISSUE TITLE
Getting `strace: |autoreset: Broken pipe` error

### ISSUE THREAD

**Issue by g105b** [deanmao/avrdude-rpi#6]
Using Raspberry Pi 3, ATMEGA328p chip is connected using TX, RX pins.

Here's a transcript of trying to `make upload`:

```
root@raspberrypi:~/sketch# make upload
-------------------------
Arduino.mk Configuration:
- [AUTODETECTED]       CURRENT_OS = LINUX
- [COMPUTED]           ARDMK_DIR = /usr/share/arduino (relative to Common.mk)
- [USER]               ARDUINO_DIR = /usr/share/arduino
- [AUTODETECTED]       ARDUINO_VERSION = 105
- [DEFAULT]            ARDUINO_SKETCHBOOK = /root/sketchbook
- [BUNDLED]            AVR_TOOLS_DIR = /usr/share/arduino/hardware/tools/avr (in Arduino distribution)
- [COMPUTED]           ARDUINO_LIB_PATH = /usr/share/arduino/libraries (from ARDUINO_DIR)
- [DEFAULT]            ARDUINO_CORE_PATH = /usr/share/arduino/hardware/arduino/cores/arduino
- [COMPUTED]           ARDUINO_VAR_PATH = /usr/share/arduino/hardware/arduino/variants (from ARDUINO_DIR)
- [COMPUTED]           BOARDS_TXT = /usr/share/arduino/hardware/arduino/boards.txt (from ARDUINO_DIR)
- [DEFAULT]            USER_LIB_PATH = /root/sketchbook/libraries (in user sketchbook)
- [DEFAULT]            PRE_BUILD_HOOK = pre-build-hook.sh
- [USER]               BOARD_TAG = uno
- [COMPUTED]           OBJDIR = build-uno (from BOARD_TAG)
- [ASSUMED]            MONITOR_BAUDRATE = 9600
- [DEFAULT]            OPTIMIZATION_LEVEL = s
- [DEFAULT]            MCU_FLAG_NAME = mmcu
- [DEFAULT]            CFLAGS_STD = -std=gnu99
- [COMPUTED]           DEVICE_PATH = /dev/ttyAMA0 (from MONITOR_PORT)
- [AUTODETECTED]       Size utility: AVR-aware for enhanced output
- [COMPUTED]           BOOTLOADER_PARENT = /usr/share/arduino/hardware/arduino/bootloaders (from ARDUINO_DIR)
-------------------------
mkdir -p build-uno
make reset
make[1]: Entering directory '/root/sketch'
/usr/bin/ard-reset-arduino  /dev/ttyAMA0
make[1]: Leaving directory '/root/sketch'
make do_upload
make[1]: Entering directory '/root/sketch'
/usr/share/arduino/hardware/tools/avr/../avrdude -q -V -D -p atmega328p -C /usr/share/arduino/hardware/tools/avr/../avrdude.conf -c arduino -b 115200 -P /dev/ttyAMA0 \
                -U flash:w:build-uno/sketch.hex:i
/usr/bin/autoreset:16: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(pin, GPIO.OUT)
done with autoreset
strace: |autoreset: Broken pipe
strace: |autoreset: Broken pipe
avrdude-original: stk500_recv(): programmer is not responding
avrdude-original: stk500_getsync() attempt 1 of 10: not in sync: resp=0x00
strace: |autoreset: Broken pipe
strace: |autoreset: Broken pipe
```

**Comment by pb66** [comment]
The "strace: |autoreset: Broken pipe" is nothing to worry about, it is a quirk of this workaround and is always present, even when 100% successful.

Is it using the correct GPIO pin? 

> Using Raspberry Pi 3, ATMEGA328p chip is connected using TX, RX pins. 

It will need a minimum of 4 connections Rx, Tx, Gnd and Reset even if powered independently. You will also need to check your voltage levels and have both devices (PI and AVR) running at 3.3v or use a level shifter.

**Comment by g105b** [comment]
1. Thanks for info regarding strace.
2. Yes, I've edited the script to use the pin I'm using. I can see the chip resets as it flashes arduino pin 13 very fast during reset.
3. Forgot to mention that the ATMEGA is powered from the pi (it's using an official breakout board).
4. If I replace the cable between the Pi and reset with an actual physical button, I can use this to program the ATMEGA in Linux or Windows environment, but have yet to be successful on the pi.
5. My problems may lie in the levels - I will implement a logic level converter circuit tonight and report back.

Thanks for your response!

**Comment by pb66** [comment]
Looks like you have most thing covered. you should also check the reset timing (See https://github.com/deanmao/avrdude-rpi/issues/4).

Note this repo doesn't seem to be maintained much these days 9since Aug 2012), so check out the other forks for more updated versions. https://github.com/deanmao/avrdude-rpi/network

**Comment by pb66** [comment]
Looks like you have most things covered. you should also check the reset timing as the original 0.12 needs to be extended to 0.3 (See https://github.com/deanmao/avrdude-rpi/issues/4).

Note this repo doesn't seem to be maintained much these days (Aug 2012?), so check out the other forks for more up to date versions. https://github.com/deanmao/avrdude-rpi/network

**Comment by g105b** [comment]
Hey, I switched to https://github.com/openenergymonitor/avrdude-rpi and it worked without any tweaks (coincidentally they also use pin 7).

Thanks for your help solving this... pretty new to me!
